# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.
# Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.3     # 증가: 0.1 -> 0.3
default_acceleration_scaling_factor: 0.3  # 증가: 0.1 -> 0.3

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  j1:
    has_velocity_limits: false
    max_velocity: 3.14000000000000001
    has_acceleration_limits: false
    max_acceleration: 3.14  # Enable acceleration limits to help Pilz planner
  j2:
    has_velocity_limits: false
    max_velocity: 3.14000000000000001
    has_acceleration_limits: false
    max_acceleration: 3.14
  j3:
    has_velocity_limits: false
    max_velocity: 3.14000000000000001
    has_acceleration_limits: false
    max_acceleration: 3.14
  j4:
    has_velocity_limits: false
    max_velocity: 3.2
    has_acceleration_limits: false
    max_acceleration: 3.2
  j5:
    has_velocity_limits: false
    max_velocity: 3.2
    has_acceleration_limits: false
    max_acceleration: 3.2
  j6:
    has_velocity_limits: false
    max_velocity: 3.2
    has_acceleration_limits: false
    max_acceleration: 3.2
